### ISSUE TITLE
先生大义

### ISSUE THREAD

**Issue by herman6b6** [qcgzxw/hass-lierda-iot#8]
我也是有这种需求，家里用的是全套精装送的利尔达智能家居。先生你这种方法感觉还是像小米那样通过云服务关联的，我个人感觉有点受限于服务商，如果小米还好不会经常挂或者挂了很快起来。我有个不成熟的方向，这个利尔达的网关怎么操作可以利用zigbee2mqtt从而达到个人服务管理呢？我还在学习，但是网上这方面的学习资料太少了，也不知道行不行，想跟你探讨一下。

**Comment by qcgzxw** [comment]
不是我的方向所以没研究 目前已知zigbee网关->利尔达服务器是通过私有mqtt协议通信。
网关后台可以选两个上游，这里可以突破，前提是要知道协议。

**Comment by qcgzxw** [comment]
https://help.senthink.com/ 仅供参考
